### ISSUE TITLE
Trial run to test workflow

### ISSUE THREAD

**Issue by maning** [osmlab/sf_building_height_import#10]

**Comment by geochetan** [comment]
We ran a trial run through the [custom tasking manager](http://tasks.openmassing.org/project/9) for 12 blocks. Out of 12 blocks, there were no issues with 5 blocks. Each task will take approximately `15-20 minutes` to review and upload the data. Noticed that only 12 multi-polygon buildings were missing from height information.

### Observations based on tasks number

#### In the [task #317](http://tasks.openmassing.org/project/9#task/317):
- The [building tagged has 9 levels](https://www.openstreetmap.org/way/436647633/history), but the import is assigning  `height = 142` meters. 
- The import has assigned `height=23` for this [building](https://www.openstreetmap.org/way/147808250/history), the beside buildings have heights greater than **40**.
- The [parking space](https://www.openstreetmap.org/way/79375233/history) is missing the building tag. So there is no height value assigned in the import.  

![screen shot 2016-11-03 at 7 27 28 pm](https://cloud.githubusercontent.com/assets/6770741/20005204/d97ad486-a2b6-11e6-9b52-31626e848240.png)
- Found 5 multi-polygon buildings missing height information in this task. 

#### In the [task #653](http://tasks.openmassing.org/project/9#task/653):
- The [building](https://www.openstreetmap.org/way/281915246/history) is half covered by the tree and the `height = 22` is derived from tree. The normal height of the building would be 6-10m in this residential area.

![screen shot 2016-11-03 at 7 45 58 pm](https://cloud.githubusercontent.com/assets/6770741/20005203/d97aed86-a2b6-11e6-9cab-6669968ec308.png)

#### In the [task #405](http://tasks.openmassing.org/project/9#task/405):
- Observed orphan nodes: There are no heights added to these temporary buildings. Not a problem though! 

![screen shot 2016-11-03 at 8 08 45 pm](https://cloud.githubusercontent.com/assets/6770741/20005202/d979eb0c-a2b6-11e6-86fc-9bf33ed45c8a.png)

#### In the [task #732](http://tasks.openmassing.org/project/9#task/732):
- **Inappropriate heights assigned** 
  - This [building](https://www.openstreetmap.org/way/279541563) seems to be having 2 levels in Mapillary. But the LIDAR height has `height=24`. Possibly it's the height of the tree. 
  
  | Satellite | Mapillary |
  | --- | --- |
  | ![image](https://cloud.githubusercontent.com/assets/12103383/19969879/31640a9e-a200-11e6-8345-ebcb49763cac.png) | ![image](https://cloud.githubusercontent.com/assets/12103383/19969891/3b76dde0-a200-11e6-87de-a735fd23b197.png) |
  - This [building](https://www.openstreetmap.org/way/279541574) height=21 seems to be too much for this building. Possibly it's the height of the tree. 
  
  | Satellite | Mapillary |
  | --- | --- |
  | ![image](https://cloud.githubusercontent.com/assets/12103383/19970185/43b5e004-a201-11e6-9b2f-3e3de81ac2e2.png) | ![image](https://cloud.githubusercontent.com/assets/12103383/19970238/68de1018-a201-11e6-9e23-64fa7c03879c.png) |

#### No issues found in the following taks 👍
1. http://tasks.openmassing.org/project/9#task/933
2. http://tasks.openmassing.org/project/9#task/614 
3. http://tasks.openmassing.org/project/9#task/336
4. http://tasks.openmassing.org/project/9#task/724
5. http://tasks.openmassing.org/project/9#task/916

**Comment by bdon** [comment]
Task #317:
1. Looks like the building takes the wrong height value from the adjacent tall tower
2. Same as above, takes value from tower to the left
3. I edited this way in OSM to have the building tag

Task #653:
1. Would median height work better for tree coverage?

Task #732:
1. Same as above
2. ditto

What about the other 3 blocks?

In general, we should investigate using the LIDAR median from the SFdata footprints - seems this would resolve many of the alignment issues you uncovered above

**Comment by bdon** [comment]
Initial results from comparing with SFdata footprint medians:

#317:
1. The footprint only has a 61% match with a SFdata footprint that is 31 meters
2. Matches SFdata with  height = 18.67 meters. Is this correct?

#653:
1. Median height is 5.64 from SFdata match

#732:
1. Median height is 14.2 from SFdata which still seems too high - probably median with trees
2. Same as above, height is 14.26 from SFdata

**Comment by geochetan** [comment]
> What about the other 3 blocks?

We found 2-3 multipolygons buildings missing the height in those 3 blocks but then everything's alright!

**Comment by geochetan** [comment]
The trail run using [new task](http://tasks.openmassing.org/project/11) using new SF opendata was successful. @calfarome and I looked into 9 tasks in an hour. We didn't notice any major flaw while importing, but we found many buildings missing height from the import. 

### Observations based on task numbers
- **Task** http://tasks.openmassing.org/project/11#task/312
   We captured some of the way ID's which were missing the height tag from the import.  
  
  ```
    - https://www.openstreetmap.org/way/252570886/history
    - https://www.openstreetmap.org/way/252570879/history
    - https://www.openstreetmap.org/way/255963531/history
    - https://www.openstreetmap.org/way/243466311/history
  ```
  
  ![missing-lot-buildings](https://cloud.githubusercontent.com/assets/6770741/20381712/9eff0c2e-acce-11e6-99c0-3f024d9d499e.png)
  
  Apart from these missing buildings, we didnt notice any issues in the task. 
- **Task** http://tasks.openmassing.org/project/11#task/329
  
  #### Missing the height for the building
  
  ```
  - https://www.openstreetmap.org/way/288486000/history
  ```
  
  #### Incorrect height - The height of the beside building is more compare to this building, but in imagery this building look like it has more levels
  
  ```
  - https://www.openstreetmap.org/way/260524901/history
  ```
  
  #### Height is already present but while importing new heights is failing
  
  ```
  - https://www.openstreetmap.org/way/260520160/history
  ```
- **Task** http://tasks.openmassing.org/project/11#task/615: Series of buildings were missing in the task otherwise no issues.

![missing-a-row](https://cloud.githubusercontent.com/assets/6770741/20463228/475d5352-af55-11e6-9fd7-1b73af877408.png)
- **Task** : http://tasks.openmassing.org/project/11#task/38
  
  ```
     There is no import building, missing the height for the buildings 
     - https://www.openstreetmap.org/way/278440587
     - https://www.openstreetmap.org/way/278440581
     - https://www.openstreetmap.org/way/281397607
     - https://www.openstreetmap.org/way/281397537
     - https://www.openstreetmap.org/way/281397610
     - https://www.openstreetmap.org/way/281397608
  ```
- **Task** http://tasks.openmassing.org/project/11#task/503 (Residential area)
  -  Missing height for the [building](https://www.openstreetmap.org/way/286651529/history)
  - **Task**  http://tasks.openmassing.org/project/11#task/457
    - Missing many buildings from the height
  
  ### No issues found in the tasks
- **Task** http://tasks.openmassing.org/project/11#task/351
- **Task**: http://tasks.openmassing.org/project/11#task/37  
- **Task**  http://tasks.openmassing.org/project/11#task/363 
  
  ### It'd be nice if we change the MapPaint style in JOSM of buildings which are height > 120
  
  ![moreheight-change-color](https://cloud.githubusercontent.com/assets/6770741/20463382/2ecf9e1a-af57-11e6-8b10-9b3d6fddb1c8.png)

@maning @bdon @talllguy

**Comment by bdon** [comment]
@chtnha @maning the missing buildings should just be the ones that don't meet a 70% match threshold.

I see that  https://www.openstreetmap.org/way/260520160/history already has a height and it's not present in the task changeset. Seems correct to me,
