### ISSUE TITLE
Review new SF building footprint

### ISSUE THREAD

**Issue by maning** [osmlab/sf_building_height_import#12]
Check if this is worthwhile to include in the current import plan.  

URL: https://sfgis-svc.sfgov.org/sfgis/San_Francisco_Bldg_withZ_20161028.zip
License:  CC0

![screen shot 2016-10-30 at 06 50 17](https://cloud.githubusercontent.com/assets/353700/19833797/35fbfc1a-9e6d-11e6-99d5-b8cdd05747e4.png)

**Comment by bdon** [comment]
One possibility is to conflate OSM footprints with the official footprints for some threshold of agreement (>75% shared area?) and then take the LIDAR max value from that. It seems worth comparing that value to the one we're using.

**Comment by bqb** [comment]
I've been made aware that the building footprints "...withZ_20161028.zip" do include updates of backyard structures in many residential neighborhoods.  This would have been interpreted from our 2015-06 through 2015-10 orthophoto.  Yes, it actually took five months to get the 2015 ortho completed.  ;^)

**Comment by bqb** [comment]
The LiDAR-derived height model has 50cm gridding, which provides about 400-600 samples for each typical residence roof in the Sunset and Richmond districts.  The airborne perspective is much more resistant to misinterpreted false fronts of buildings than a StreetView curb-level or Pictometry/Eagle View oblique measure of height.  https://goo.gl/maps/cwpWjTXG8CD2  for example

**Comment by maning** [comment]
I reviewed the **San_Francisco_Bldg_withZ_20161028.zip** data by comparing with the same [samples we used previously](https://github.com/osmlab/sf_building_height_import/issues/7).  For the purpose of comparison, I used the `gnd1st_delta` field as the height value.  The **overall variance is not very big, the total average is ~1.8 meters and there is good agreement with both samples**.  

![screen shot 2016-11-02 at 16 19 23](https://cloud.githubusercontent.com/assets/353700/19927304/33e329c6-a11f-11e6-8a96-20e7635b4a76.png)

There were edge cases where LiDAR derived heights differ from New SF data, primarily when the building outline is different or slightly offset.  Some examples below (yellow-OSM, purple-SF gov data).

![almost_match](https://cloud.githubusercontent.com/assets/353700/19927342/56f0c0c2-a11f-11e6-8ecc-106ee512b091.png)<br>_Almost perfect match of geometry and height._

![osm_misalingned](https://cloud.githubusercontent.com/assets/353700/19927389/82ec3d28-a11f-11e6-8d8e-6f4a45319456.png)<br>_OSM misaligned, SF data height is greater by 2 m._

![adjacent_to_tall](https://cloud.githubusercontent.com/assets/353700/19927412/9f856aa4-a11f-11e6-9508-b1b28a9ee766.png)<br>_OSM not properly traced, the higher adjacent building height was included resulting to a height difference of 44 m._

![simple_but complex](https://cloud.githubusercontent.com/assets/353700/19927426/ac38b076-a11f-11e6-85a5-b3be2a489376.png)<br>_Complex buildings in SF data, simplified trace in OSM._

**Open questions**
- New SF data seems to have a much more accurate height compared to our LiDAR derived heights, but the measurements were based on **median** values.  Per OSM's convention, we should use the maximum height.  How do we reconcile this?
- Although this is rare, some  OSM buildings were poorly traced when compared to SF data and Bing imagery.  As a result, LiDAR derived heights might be wrong.  Should we included geometry  from SF data as part of the import?  This will change our conversion tools and eventually or workflow.
  
  **Process of evaluation**
- Convert SF geodatabase to shapefile and retroject to EPSG:4326. 
  `ogr2ogr -f "ESRI Shapefile" -t_srs EPSG:4326 sf13m_BldgFoot_withZ_20161005_pgz_4326.shp SF_Bldg_201610.gdb "sf13m_BldgFoot_withZ_20161005_pgz"`
- Load both OSM data and SF data in QGIS.
- Compare height results for each sample in this [spreadsheet](https://docs.google.com/spreadsheets/d/10Chpr0ysHJxmnBSpTLiH94FafDV3INTXhTU3fWK8h_A/edit).

Notes
- `gnd1st_delta` - was defined as the "difference of median first return surface - minimum bare earth surface in meters".

@bdon @chtnha @bqb

**Comment by bdon** [comment]
I'm apprehensive about adding, removing or replacing geometry as this will significantly increase the scope of this project, and also could overwrite mapper's hard work (suppose there are places where the OSM geometry is better or newer than SF?)

Here's a proposal: we keep everything the same as before, but only tag buildings that have a high geometry agreement with the SF gov data. That way we don't tag buildings that potentially wrong height values from being misaligned.

I wonder if we set the threshold at 80% agreement, for example, what % of the current ~150,000 buildings are still valid. Will investigate

**Comment by bqb** [comment]
The SF buildings contain over 30 zonal statistics to provide options beyond the most robust median.  The values emphasize absolute elevations first, and various estimates for building height can be derived.
The "gnd" ground surface model was natural neighbor interpolated from only ground-classed LiDAR returns.  So every building footprint had no ground returns beneath it, and that model often interpolates from front to back edges of the structure.

Our preferred statistic would be "hgt_Median_m" because that is the median of grid-cell-wise separation between the ground and first-return surfaces.  If better agreement is found with "gnd1st_delta_m" then that might suggest a bias toward greater height makes a better fit.

These sort of areas motivated our selection of input building footprints
![osm_contrast_difference](https://cloud.githubusercontent.com/assets/5401492/19943935/da2b36c6-a0f6-11e6-90e4-ffe03dd7fe5a.jpg)

The building height model for this area was thus
![osm_contrast_1o3](https://cloud.githubusercontent.com/assets/5401492/19943951/f14701f0-a0f6-11e6-9f81-6c3031af7792.jpg)

The OSM footprints that I presume were from Bing roooftop traces fit like this
![osm_contrast_2o3](https://cloud.githubusercontent.com/assets/5401492/19943981/0dda8396-a0f7-11e6-8661-0684483c7435.jpg)

And the DataSF footprints that had been derived from building masses at the time of LiDAR acquisition fit more closely.
![osm_contrast_3o3](https://cloud.githubusercontent.com/assets/5401492/19944006/2e1f4394-a0f7-11e6-886e-2127068b7522.jpg)

Again, the statistics have been oriented mostly toward placing buildings at absolute heights, and the Z elevation of the 2D polygons has been set to minimum intersected bare-earth elevation.  The median roof elevation from first-return surface is rather robust for most city structures that aren't pyramid-shaped or severely overhung by trees.

If ogr2ogr is used to bring the footprints into WGS84 geographic/4326 there will likely be a systematic ~2 foot horizontal offset relative to the NAD 1983 (2011) reference system used in our 7131 and 7132 systems.  Our city orthos turn out to have been delivered with that GRS since 2014, although we only figured that out a couple of months ago.  The epoch difference (2010 - 1984) of 26 years actually adds up noticeably.

**Comment by bdon** [comment]
If we limit the buildings we tag to only those with an area threshold match vs. the SFdata footprints:

```
select f.* from features f, wm84_bldgfoot_withz_20161005_pgz w 
    where ST_Intersects(f.geometry, w.wkb_geometry) 
    and st_area(st_intersection(f.geometry, w.wkb_geometry)) / st_area(f.geometry) > 0.8 
    and st_area(st_intersection(f.geometry, w.wkb_geometry)) / st_area(w.wkb_geometry) > 0.8 
```

Out of a total of 165825 tagged OSM buildings:
0.6: 148435 (90%)
0.7: 142695 (86%)
0.8: 126837 (76%)
0.9: 91926 (55%)

**Comment by bdon** [comment]
Thoughts on median/max:

If we continue to use the LIDAR value calculated from OSM footprints, the median accuracy is adversely affected by the footprint being misaligned - consider an OSM footprint shifted 2 meters to the east relative to the LIDAR building. The median calculation then includes all those 0 or street level pixels that shouldn't be included

**Comment by maning** [comment]
We are now using SF building data median height.
