### ISSUE TITLE
change MapCSS JOSM style

### ISSUE THREAD

**Issue by bdon** [osmlab/sf_building_height_import#15]

**Comment by maning** [comment]
Still WIP, I've modified the [existing style to show 4 levels of height](https://github.com/osmlab/sf_building_height_import/commit/a047388f936bce8ee4027088c534394e785e95ec) (low rise, medium rise, high rise, skyscrapers).  Screenshots below:

![screen shot 2016-11-10 at 17 02 33](https://cloud.githubusercontent.com/assets/353700/20175274/ee48b5a8-a767-11e6-8d8a-a2e45d2d6943.png)
![screen shot 2016-11-10 at 16 59 27](https://cloud.githubusercontent.com/assets/353700/20175275/ee4a88a6-a767-11e6-904e-8664632a3861.png)

@chtnha @bdon

**Comment by bdon** [comment]
Looks good! Maybe is there a way to change the control points on the building outlines from yellow to the same color?

**Comment by maning** [comment]
>  control points on the building outlines from yellow to the same color?

Not sure what you mean, is this the node that is shared by two ways in black? ![screen shot 2016-11-11 at 18 07 47](https://cloud.githubusercontent.com/assets/353700/20215386/d4543e92-a839-11e6-9ede-fb6db8d8595c.png)

Personally, I like it since it shows that data is valid if 2 buildings share a wall. Colors are arbitrary BTW.

**Comment by bdon** [comment]
OK, good point on buildings sharing a wall. 👍

**Comment by maning** [comment]
Done here, re-open if style needs improvement.
